# Makefile.in generated by automake 1.11.3 from Makefile.am.
# modules/jit_ocaml/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



#
# Scilab ( http://www.scilab.org/ ) - This file is part of Scilab
# Copyright (C) DIGITEO - 2010 - Allan CORNET
# Copyright (C) DIGITEO - 2010 - Bruno JOFRET
#
# This file must be used under the terms of the CeCILL.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution.  The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL_V2-en.txt
#

# Scilab ( http://www.scilab.org/ ) - This file is part of Scilab
# Copyright (C) 2006-2008 - INRIA - Sylvestre LEDRU <sylvestre.ledru@inria.fr>
# Copyright (C) 2008      - INRIA - Pierre MARECHAL <pierre.marechal@inria.fr>
#
# This file must be used under the terms of the CeCILL.
# This source file is licensed as described in the file COPYING, which
# you should have received as part of this distribution.  The terms
# are also available at
# http://www.cecill.info/licences/Licence_CeCILL_V2-en.txt
#

##########
### Makefile included stuff
### Target, variable, suffixes which are supposed to be useful in every makefile.am
##########



pkgdatadir = $(datadir)/scilab
pkgincludedir = $(includedir)/scilab
pkglibdir = $(libdir)/scilab
pkglibexecdir = $(libexecdir)/scilab
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
DIST_COMMON = $(srcdir)/.depend_ocaml $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/Makefile.incl.am
am__append_1 = java
subdir = modules/jit_ocaml
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/backtrace.m4 \
	$(top_srcdir)/m4/compiler.m4 $(top_srcdir)/m4/docbook.m4 \
	$(top_srcdir)/m4/doxygen.m4 $(top_srcdir)/m4/eigen.m4 \
	$(top_srcdir)/m4/fftw.m4 $(top_srcdir)/m4/fortran.m4 \
	$(top_srcdir)/m4/giws.m4 $(top_srcdir)/m4/hdf5.m4 \
	$(top_srcdir)/m4/intel_compiler.m4 \
	$(top_srcdir)/m4/java-thirdparty.m4 $(top_srcdir)/m4/java.m4 \
	$(top_srcdir)/m4/largefile.m4 $(top_srcdir)/m4/lib-ld.m4 \
	$(top_srcdir)/m4/libsmath.m4 $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/libxml2.m4 $(top_srcdir)/m4/ltoptions.m4 \
	$(top_srcdir)/m4/ltsugar.m4 $(top_srcdir)/m4/ltversion.m4 \
	$(top_srcdir)/m4/lt~obsolete.m4 $(top_srcdir)/m4/macosx.m4 \
	$(top_srcdir)/m4/ocaml.m4 $(top_srcdir)/m4/pcre.m4 \
	$(top_srcdir)/m4/pkg.m4 $(top_srcdir)/m4/relocatable.m4 \
	$(top_srcdir)/m4/swig.m4 $(top_srcdir)/m4/symlinks.m4 \
	$(top_srcdir)/m4/tcltk.m4 $(top_srcdir)/m4/umfpack.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
mkinstalldirs = $(SHELL) $(top_srcdir)/config/mkinstalldirs
CONFIG_HEADER = $(top_builddir)/modules/core/includes/machine.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(pkglibdir)" \
	"$(DESTDIR)$(libscijit_ocaml_la_etcdir)" \
	"$(DESTDIR)$(libscijit_ocaml_la_rootdir)"
LTLIBRARIES = $(pkglib_LTLIBRARIES)
libscijit_ocaml_la_DEPENDENCIES = libscijit_ocaml-runtime.o
am__objects_1 = libscijit_ocaml_la-scicaml_ast2string.lo \
	libscijit_ocaml_la-scicaml_string2ast.lo
am_libscijit_ocaml_la_OBJECTS = $(am__objects_1)
libscijit_ocaml_la_OBJECTS = $(am_libscijit_ocaml_la_OBJECTS)
DEFAULT_INCLUDES = -I. -I$(top_builddir)/modules/core/includes
depcomp = $(SHELL) $(top_srcdir)/config/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
	$(LDFLAGS) -o $@
SOURCES = $(libscijit_ocaml_la_SOURCES)
DIST_SOURCES = $(libscijit_ocaml_la_SOURCES)
DATA = $(libscijit_ocaml_la_etc_DATA) $(libscijit_ocaml_la_root_DATA)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/lefessan/GIT/RICHELIEU/scilab/scilab/config/missing --run aclocal-1.11
ALL_LINGUAS = en_US fr_FR zh_CN zh_TW ru_RU ca_ES de_DE es_ES pt_BR ja_JP it_IT uk_UA pl_PL cs_CZ
ALL_LINGUAS_DOC = en_US fr_FR pt_BR ja_JP ru_RU
AMTAR = $${TAR-tar}
ANT = /usr/bin/ant
ANTLR = /usr/share/java/antlr.jar
AR = ar
ARPACK_LIBS = -larpack
ASM3 = /usr/share/java/asm3.jar
AUTOCONF = ${SHELL} /home/lefessan/GIT/RICHELIEU/scilab/scilab/config/missing --run autoconf
AUTOHEADER = ${SHELL} /home/lefessan/GIT/RICHELIEU/scilab/scilab/config/missing --run autoheader
AUTOMAKE = ${SHELL} /home/lefessan/GIT/RICHELIEU/scilab/scilab/config/missing --run automake-1.11
AVALON_FRAMEWORK = /usr/share/java/avalon-framework.jar
AWK = gawk
BATIK = /usr/share/java/batik-all.jar
BLAS_LIBS = -lblas
CC = gcc
CCACHE = 
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CHECKSTYLE = 
COBERTURA = 
COMMONS_BEANUTILS = /usr/share/java/commons-beanutils.jar
COMMONS_IO = /usr/share/java/commons-io.jar
COMMONS_LOGGING = /usr/share/java/commons-logging.jar
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEMOTOOLS_ENABLE = yes
DEPDIR = .deps
DOCBOOK_ROOT = /usr/share/sgml/docbook/stylesheet/xsl/nwalsh
DOXYGEN_BIN = 
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EIGEN_CPPFLAGS = -I/usr/include/eigen3/
EXEEXT = 
F77 = gfortran
FFLAGS = -g -O2
FFTW3_LIB = -lfftw3
FFTW_ENABLE = yes
FGREP = /bin/grep -F
FLEXDOCK = /usr/share/java/flexdock-1.2.0.jar
FLIBS =  -L/usr/lib/gcc/x86_64-linux-gnu/4.6 -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/4.6/../../.. -lpthread -ldl -lcurses -lgfortran -lm -lquadmath
FOP = /usr/share/java/fop.jar
GENHTML = 
GETTEXT_MACRO_VERSION = 0.18
GIWS_BIN = 
GLUEGEN2_RT = /usr/share/java/gluegen2-rt.jar
GMSGFMT = /usr/bin/msgfmt
GMSGFMT_015 = /usr/bin/msgfmt
GRAPHICS_ENABLE = yes
GREP = /bin/grep
GUI_ENABLE = yes
HDF5_CFLAGS = 
HDF5_LIBS = -lhdf5
HELP_ENABLE = yes
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
INTLLIBS = 
INTL_MACOSX_LIBS = 
JAR = /usr/lib/jvm/java-6-openjdk-amd64/bin/jar
JAVA = /usr/lib/jvm/java-6-openjdk-amd64/bin/java
JAVAC = /usr/lib/jvm/java-6-openjdk-amd64/bin/javac
JAVAC_DEBUG = off
JAVADOC = /usr/lib/jvm/java-6-openjdk-amd64/bin/javadoc
JAVAH = /usr/lib/jvm/java-6-openjdk-amd64/bin/javah
JAVASCI_ENABLE = yes
JAVA_ENABLE = yes
JAVA_G = /usr/lib/jvm/java-6-openjdk-amd64/bin/java
JAVA_HOME = /usr/lib/jvm/java-6-openjdk-amd64
JAVA_JNI_INCLUDE = -I/usr/lib/jvm/java-6-openjdk-amd64/include -I/usr/lib/jvm/java-6-openjdk-amd64/include/linux
JAVA_JNI_LIBS = -L/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64 -ljava -lverify -L/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server -ljvm
JDB = /usr/lib/jvm/java-6-openjdk-amd64/bin/jdb
JEUCLID_CORE = /usr/share/java/jeuclid-core.jar
JGRAPHX = /usr/share/java/jgraphx-1.8.0.1.jar
JHALL = /usr/share/java/jhall.jar
JLATEXMATH = /usr/share/java/jlatexmath.jar
JLATEXMATH_FOP = /usr/share/java/jlatexmath-fop.jar
JOGL2 = /usr/share/java/jogl2.jar
JROSETTA_API = /usr/share/java/jrosetta-API.jar
JROSETTA_ENGINE = /usr/share/java/jrosetta-engine.jar
JUNIT4 = /usr/share/java/junit4.jar
LAPACK_LIBS = -llapack
LCOV = 
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LEX = 
LEXLIB = 
LEX_OUTPUT_ROOT = 
LIBICONV = -liconv
LIBINTL = 
LIBM = -lm
LIBOBJS = 
LIBS = -lpthread -ldl -lcurses  -lm
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LOGGING_LEVEL = SEVERE
LOOKS = /usr/share/java/looks.jar
LTLIBICONV = -liconv
LTLIBINTL = 
LTLIBOBJS = 
MAINT = 
MAKEINFO = ${SHELL} /home/lefessan/GIT/RICHELIEU/scilab/scilab/config/missing --run makeinfo
MATIO_CFLAGS =  
MATIO_ENABLE = yes
MATIO_LIBS = -lmatio -lz  
MKDIR_P = /bin/mkdir -p
MSGCAT = /usr/bin/msgcat
MSGFMT = /usr/bin/msgfmt
MSGFMT_015 = /usr/bin/msgfmt
MSGMERGE = /usr/bin/msgmerge
NM = nm
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OCAMLC = ocamlc
OCAMLDEP = ocamldep
OCAMLLEX = ocamllex
OCAMLOPT = ocamlopt
OCAMLYACC = ocamlyacc
OPENMP_CFLAGS = -fopenmp
OPENMP_CXXFLAGS = -fopenmp
OPENMP_ENABLE = yes
OPENMP_LIBS = -lgomp
OTOOL = 
OTOOL64 = 
PACKAGE = scilab
PACKAGE_BUGREPORT = http://bugzilla.scilab.org/
PACKAGE_NAME = Scilab
PACKAGE_STRING = Scilab 6
PACKAGE_TARNAME = scilab
PACKAGE_URL = 
PACKAGE_VERSION = 6
PATH_SEPARATOR = :
PCRE_CFLAGS =  
PCRE_CONFIG = pcre-config
PCRE_LIBS = -L/usr/lib/x86_64-linux-gnu -lpcreposix -lpcre
PCRE_VERSION = 8.12
PKG_CONFIG = /usr/bin/pkg-config
POSUB = po
POW_LIB = 
PYTHON = 
RANLIB = ranlib
RELOCATABLE = no
RT_LIB = -lrt
SAXON = /usr/share/java/saxon.jar
SCILAB_BINARY_VERSION = 6.0.0
SCILAB_LIBRARY_VERSION = 6:0:0
SCILAB_VERSION_MAINTENANCE = 0
SCILAB_VERSION_MAJOR = 6
SCILAB_VERSION_MINOR = 0
SCIRENDERER = /usr/share/java/scirenderer-1.0.2.jar
SCI_CFLAGS = -D_LARGEFILE64_SOURCE -DNDEBUG -m64 -fno-stack-protector
SCI_CXXFLAGS = -DNDEBUG -fno-stack-protector
SCI_FFLAGS = -DNDEBUG -m64 -fPIC
SCI_LDFLAGS = -lstdc++ -Wl,--no-as-needed
SED = /bin/sed
SET_MAKE = 
SET_RELOCATABLE = 
SHELL = /bin/bash
SKINLF = /usr/share/java/skinlf.jar
SPLINT = no
STRIP = strip
SWIG_BIN = 
SWIG_JAVA = 
SWIG_RUNTIME_LIBS_DIR = 
TCLTK_LIBS =  -L/usr/lib -ltk8.5   -L/usr/lib -ltcl8.5  -ldl
TCL_INC_PATH = -I/usr/include/tcl8.5
TK_INC_PATH = -I/usr/include/tcl8.5
UMFPACK_ENABLE = yes
UMFPACK_LIB = -lumfpack -lamd
USE_NLS = yes
VERSION = 6
WITH_OCAML = 
WITH_TKSCI = yes
XCOS_ENABLE = yes
XGETTEXT = /usr/bin/xgettext
XGETTEXT_015 = /usr/bin/xgettext
XGETTEXT_EXTRA_OPTIONS = 
XMKMF = 
XMLGRAPHICS_COMMONS = /usr/share/java/xmlgraphics-commons.jar
XML_APIS_EXT = /usr/share/java/xml-apis-ext.jar
XML_CONFIG = xml2-config
XML_FLAGS = -I/usr/include/libxml2
XML_LIBS = -L/usr/lib/x86_64-linux-gnu -lxml2
XML_VERSION = 2.7.8
X_CFLAGS = 
X_EXTRA_LIBS = 
X_LIBS = 
X_PRE_LIBS =  -lSM -lICE
YACC = 
YFLAGS = 
abs_builddir = /home/lefessan/GIT/RICHELIEU/scilab/scilab/modules/jit_ocaml
abs_srcdir = /home/lefessan/GIT/RICHELIEU/scilab/scilab/modules/jit_ocaml
abs_top_builddir = /home/lefessan/GIT/RICHELIEU/scilab/scilab
abs_top_srcdir = /home/lefessan/GIT/RICHELIEU/scilab/scilab
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
ac_ct_F77 = gfortran
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
cxx_present = yes
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/lefessan/GIT/RICHELIEU/scilab/scilab/config/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /home/lefessan/GIT/RICHELIEU/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../../
top_builddir = ../..
top_srcdir = ../..
yacc_present = 

#### Target ######
modulename = jit_ocaml

#### jit_ocaml : Conf files ####
libscijit_ocaml_la_rootdir = $(mydatadir)
libscijit_ocaml_la_root_DATA = license.txt

#### jit_ocaml : init scripts ####
libscijit_ocaml_la_etcdir = $(mydatadir)/etc
libscijit_ocaml_la_etc_DATA = etc/jit_ocaml.quit \
			  etc/jit_ocaml.start


# Where all the Scilab stuff is installed (macros, help, ...)
mydatadir = $(pkgdatadir)/modules/$(modulename)

# Set AM_* SCI detected settings
AM_CPPFLAGS = $(SCI_CPPFLAGS)
AM_CFLAGS = $(SCI_CFLAGS)
AM_CXXFLAGS = $(SCI_CXXFLAGS)
# append includes to AM_FFLAGS to manage fortran includes
AM_FFLAGS = $(SCI_FFLAGS) -I$(top_srcdir)/modules/core/includes/

# Tag shared libraries with the Scilab version
AM_LDFLAGS = $(SCI_LDFLAGS) -version-number $(SCILAB_LIBRARY_VERSION)

# splint options
SPLINT_OPTIONS = -weak -booltype BOOL

########################### JAVA ######################################
#### We are delegating java compilation to ant... Thanks to that
#### the procedure will be the same with Microsoft Windows (C)
#### and Linux/Unix
#######################################################################
TARGETS_ALL = $(am__append_1)

################ MACROS ######################
# Rule to build a macro
# NOT USED  AT THE MOMENT

########## COMMON
SUFFIXES = .sci .ml .mli .mll .mly .cmi .cmx

########### INSTALL DOCUMENTATION ###################

# Install documentation files into the right target
# We do not use the automake mechanism (libxxxx_la_help_fr_DATA) because
# automake needs the html files to be present which is not the case when
# we are building Scilab

# Where it should be installed
pkgdocdir = $(mydatadir)

# What is the mask of the help source
DOCMASKXML = *.xml

# What is the mask of the MathML sources
DOCMASKMML = *.mml

########### INSTALL DATA ###################
# Install macros, help & demos
# Where it should be installed
pkgmacrosdir = $(mydatadir)
# Which directory we process
MACRODIRS = macros/
# Mask of the Scilab sources macros
MACROMASK = *.sci
# Mask of the Scilab executable sources macros
MACROBUILDMASK = *.sce
# Mask of the Scilab compiled macros
MACROBINMASK = *.bin
# List of the standard directory for tests
TESTS_DIR = tests/benchmarks tests/nonreg_tests tests/unit_tests tests/java
# Where the demos should be installed
pkgdemosdir = $(mydatadir)
# List of the standard directory for demos
DEMOS_DIR = demos
# List of the standard directory for examples
EXAMPLES_DIR = examples
# Where to export JAVA archives (.jar)
JARDIR = jar/
# JAR files mask
JARMASK = *.jar
# Chapter file 
HELP_CHAPTERDIR = help/
HELP_CHAPTERFILE = addchapter.sce
HELP_CHAPTERLANG = en_US fr_FR pt_BR
JIT_OCAML_CPP_SOURCES = \
			src/cpp/scicaml_ast2string.cpp \
			src/cpp/scicaml_string2ast.cpp


#JIT_OCAML_C_SOURCES = \
#			src/c/jit_callback.c
libscijit_ocaml_la_CFLAGS = -I$(srcdir)/includes
libscijit_ocaml_la_CPPFLAGS = \
	-I$(srcdir)/includes \
        -I$(top_srcdir)/libs/MALLOC/includes \
	-I$(top_srcdir)/modules/elementary_functions/includes \
	-I$(top_srcdir)/modules/localization/includes \
	-I$(top_srcdir)/modules/operations/includes \
	-I$(top_srcdir)/modules/symbol/includes \
	-I$(top_srcdir)/modules/ast/includes \
	-I$(top_srcdir)/modules/types/includes \
	-I$(top_srcdir)/modules/parse/includes \
	-I$(top_srcdir)/modules/system_env/includes \
	-I$(top_srcdir)/modules/functions_manager/includes \
	-I$(top_srcdir)/modules/string/includes \
	-I$(top_srcdir)/modules/threads/includes \
        -I$(top_srcdir)/modules/api_scilab/includes \
        -I$(top_srcdir)/modules/console/includes \
        -I$(top_srcdir)/modules/output_stream/includes \
        -I$(top_srcdir)/libs/dynamiclibrary/includes \
	-I src/cpp \
	$(EIGEN_CPPFLAGS) \
	$(AM_CPPFLAGS)

pkglib_LTLIBRARIES = libscijit_ocaml.la
#BUILT_SOURCES = libscijit_ocaml-runtime.a
#
libscijit_ocaml_la_LIBADD = libscijit_ocaml-runtime.o
libscijit_ocaml_la_SOURCES = $(JIT_OCAML_CPP_SOURCES)
OCAMLC_WHERE := `$(OCAMLOPT) -where`
OCAML_AST_MLS = \
	src/ocaml/scilabAst.ml \
	src/ocaml/scilabTypes.ml \
	src/ocaml/scilabAstPrinter.ml

OCAML_AST_MLIS = \
	src/ocaml/scilabAstPrinter.mli

OCAML_SCILAB_MLS = \
	src/ocaml/scilabString2Ast.ml \
	src/ocaml/scilabCallbacks.ml

OCAML_SCILAB_MLIS = \
	src/ocaml/scilabString2Ast.mli \
	src/ocaml/scilabCallbacks.mli

OCAML_MLS = \
	$(OCAML_AST_MLS) \
	$(OCAML_SCILAB_MLS)

OCAML_MLIS = \
	$(OCAML_AST_MLIS) \
	$(OCAML_SCILAB_MLIS)

OCAML_CMIS = $(OCAML_MLS:.ml=.cmi) $(OCAML_MLIS:.mli=.cmi)
OCAML_CMXS = $(OCAML_MLS:.ml=.cmx)
OCAML_OBJS = $(OCAML_MLS:.ml=.o)
OCAML_INCL = -I src/ocaml
OPTFLAGS = -c -fPIC $(OCAML_INCL)
CLEANFILES = \
	$(OCAML_CMIS)  \
	$(OCAML_CMXS)  \
	$(OCAML_OBJS)  \
	jit_ocaml.o \
	libasmrun.a

all: all-am

.SUFFIXES:
.SUFFIXES: .sci .ml .mli .mll .mly .cmi .cmx .bin .cpp .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(top_srcdir)/Makefile.incl.am $(srcdir)/.depend_ocaml $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign modules/jit_ocaml/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign modules/jit_ocaml/Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;
$(top_srcdir)/Makefile.incl.am $(srcdir)/.depend_ocaml:

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):
install-pkglibLTLIBRARIES: $(pkglib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	test -z "$(pkglibdir)" || $(MKDIR_P) "$(DESTDIR)$(pkglibdir)"
	@list='$(pkglib_LTLIBRARIES)'; test -n "$(pkglibdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(pkglibdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(pkglibdir)"; \
	}

uninstall-pkglibLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(pkglib_LTLIBRARIES)'; test -n "$(pkglibdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(pkglibdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(pkglibdir)/$$f"; \
	done

clean-pkglibLTLIBRARIES:
	-test -z "$(pkglib_LTLIBRARIES)" || rm -f $(pkglib_LTLIBRARIES)
	@list='$(pkglib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libscijit_ocaml.la: $(libscijit_ocaml_la_OBJECTS) $(libscijit_ocaml_la_DEPENDENCIES) $(EXTRA_libscijit_ocaml_la_DEPENDENCIES) 
	$(CXXLINK) -rpath $(pkglibdir) $(libscijit_ocaml_la_OBJECTS) $(libscijit_ocaml_la_LIBADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/libscijit_ocaml_la-scicaml_ast2string.Plo
include ./$(DEPDIR)/libscijit_ocaml_la-scicaml_string2ast.Plo

.cpp.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Plo
#	source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LTCXXCOMPILE) -c -o $@ $<

libscijit_ocaml_la-scicaml_ast2string.lo: src/cpp/scicaml_ast2string.cpp
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libscijit_ocaml_la_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT libscijit_ocaml_la-scicaml_ast2string.lo -MD -MP -MF $(DEPDIR)/libscijit_ocaml_la-scicaml_ast2string.Tpo -c -o libscijit_ocaml_la-scicaml_ast2string.lo `test -f 'src/cpp/scicaml_ast2string.cpp' || echo '$(srcdir)/'`src/cpp/scicaml_ast2string.cpp
	$(am__mv) $(DEPDIR)/libscijit_ocaml_la-scicaml_ast2string.Tpo $(DEPDIR)/libscijit_ocaml_la-scicaml_ast2string.Plo
#	source='src/cpp/scicaml_ast2string.cpp' object='libscijit_ocaml_la-scicaml_ast2string.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libscijit_ocaml_la_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o libscijit_ocaml_la-scicaml_ast2string.lo `test -f 'src/cpp/scicaml_ast2string.cpp' || echo '$(srcdir)/'`src/cpp/scicaml_ast2string.cpp

libscijit_ocaml_la-scicaml_string2ast.lo: src/cpp/scicaml_string2ast.cpp
	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libscijit_ocaml_la_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT libscijit_ocaml_la-scicaml_string2ast.lo -MD -MP -MF $(DEPDIR)/libscijit_ocaml_la-scicaml_string2ast.Tpo -c -o libscijit_ocaml_la-scicaml_string2ast.lo `test -f 'src/cpp/scicaml_string2ast.cpp' || echo '$(srcdir)/'`src/cpp/scicaml_string2ast.cpp
	$(am__mv) $(DEPDIR)/libscijit_ocaml_la-scicaml_string2ast.Tpo $(DEPDIR)/libscijit_ocaml_la-scicaml_string2ast.Plo
#	source='src/cpp/scicaml_string2ast.cpp' object='libscijit_ocaml_la-scicaml_string2ast.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(LIBTOOL)  --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(libscijit_ocaml_la_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o libscijit_ocaml_la-scicaml_string2ast.lo `test -f 'src/cpp/scicaml_string2ast.cpp' || echo '$(srcdir)/'`src/cpp/scicaml_string2ast.cpp

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
install-libscijit_ocaml_la_etcDATA: $(libscijit_ocaml_la_etc_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(libscijit_ocaml_la_etcdir)" || $(MKDIR_P) "$(DESTDIR)$(libscijit_ocaml_la_etcdir)"
	@list='$(libscijit_ocaml_la_etc_DATA)'; test -n "$(libscijit_ocaml_la_etcdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(libscijit_ocaml_la_etcdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(libscijit_ocaml_la_etcdir)" || exit $$?; \
	done

uninstall-libscijit_ocaml_la_etcDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(libscijit_ocaml_la_etc_DATA)'; test -n "$(libscijit_ocaml_la_etcdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(libscijit_ocaml_la_etcdir)'; $(am__uninstall_files_from_dir)
install-libscijit_ocaml_la_rootDATA: $(libscijit_ocaml_la_root_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(libscijit_ocaml_la_rootdir)" || $(MKDIR_P) "$(DESTDIR)$(libscijit_ocaml_la_rootdir)"
	@list='$(libscijit_ocaml_la_root_DATA)'; test -n "$(libscijit_ocaml_la_rootdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(libscijit_ocaml_la_rootdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(libscijit_ocaml_la_rootdir)" || exit $$?; \
	done

uninstall-libscijit_ocaml_la_rootDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(libscijit_ocaml_la_root_DATA)'; test -n "$(libscijit_ocaml_la_rootdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(libscijit_ocaml_la_rootdir)'; $(am__uninstall_files_from_dir)

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) check-local
check: check-am
all-am: Makefile $(LTLIBRARIES) $(DATA) all-local
installdirs:
	for dir in "$(DESTDIR)$(pkglibdir)" "$(DESTDIR)$(libscijit_ocaml_la_etcdir)" "$(DESTDIR)$(libscijit_ocaml_la_rootdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool clean-local \
	clean-pkglibLTLIBRARIES mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-local distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-data-local install-libscijit_ocaml_la_etcDATA \
	install-libscijit_ocaml_la_rootDATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-pkglibLTLIBRARIES

install-html: install-html-am

install-html-am: install-html-local

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-libscijit_ocaml_la_etcDATA \
	uninstall-libscijit_ocaml_la_rootDATA \
	uninstall-pkglibLTLIBRARIES

.MAKE: check-am install-am install-strip

.PHONY: CTAGS GTAGS all all-am all-local check check-am check-local \
	clean clean-generic clean-libtool clean-local \
	clean-pkglibLTLIBRARIES ctags distclean distclean-compile \
	distclean-generic distclean-libtool distclean-local \
	distclean-tags distdir dvi dvi-am html html-am info info-am \
	install install-am install-data install-data-am \
	install-data-local install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am \
	install-html-local install-info install-info-am \
	install-libscijit_ocaml_la_etcDATA \
	install-libscijit_ocaml_la_rootDATA install-man install-pdf \
	install-pdf-am install-pkglibLTLIBRARIES install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-libscijit_ocaml_la_etcDATA \
	uninstall-libscijit_ocaml_la_rootDATA \
	uninstall-pkglibLTLIBRARIES


# This target enables tests for Scilab
check-local: $(top_builddir)/scilab-bin test
	if test -d $(mydatadir)/tests; then \
	  @COMMAND="try test_run('$(modulename)');catch exit(-1);end;exit(0)"; export LANG=C; $(top_builddir)/bin/scilab -nwni -nb -e "$$COMMAND"; \
	fi
check-code:
	if test -f build.xml; then \
		$(ANT) checkstyle; \
	fi
	if test -x "$(SPLINT)"; then \
		$(SPLINT) $(SPLINT_OPTIONS) -I$(top_srcdir)/modules/core/includes/ -I$(top_srcdir)/libs/MALLOC/includes/ -I$(top_srcdir)/modules/localization/includes/ $(INCLUDE_FLAGS) $(CHECK_SRC); \
	fi
java:
# Some configurations needs to export JAVA_HOME in the current env
	@if test "$(JAVA_HOME)"; then export JAVA_HOME=$(JAVA_HOME); fi; \
	if test -z "$(USEANT)"; then USEANT=0; else USEANT=1; fi; \
	if test -f build.xml -a $$USEANT -eq 1; then \
		$(ANT); \
	fi

clean-java:
# Some configurations needs to export JAVA_HOME in the current env
	@if test "$(JAVA_HOME)"; then export JAVA_HOME=$(JAVA_HOME); fi; \
	if test -z "$(USEANT)"; then USEANT=0; else USEANT=1; fi; \
	if test -f build.xml -a $$USEANT -eq 1; then \
		$(ANT) clean; \
	fi;

# If the user request for the SWIG generation of the wrappers Java => C/C++ 
# We call the target swig-build on the variable SWIG_WRAPPERS

#swig: $(SWIG_WRAPPERS)
#	@SWIG_PACKAGENAME=org.scilab.modules.$(modulename); \
#	SWIG_OUTDIR=src/java/org/scilab/modules/$(modulename)/; \
#	if test -n "$(SWIG_WRAPPERS)"; then \
#		for file in $(SWIG_WRAPPERS) ; do \
#			echo "Swig process of $$file ..."; \
#			$(SWIG_BIN) $(SWIG_JAVA) -package $$SWIG_PACKAGENAME  -outdir $$SWIG_OUTDIR $$file; \
#		done; \
#	fi

# If the user request for the SWIG generation of the wrappers Java => C/C++ 
# We call the target swig-build on the variable SWIG_WRAPPERS

#giws: $(GIWS_WRAPPERS)
#	@GIWS_OUTPUTDIR=src/jni/;\
#	if test -n "$(GIWS_WRAPPERS)"; then \
#		for file in $(GIWS_WRAPPERS) ; do \
#			echo "GIWS process of $$file ..."; \
#			$(GIWS_BIN) --disable-return-size-array --output-dir $$GIWS_OUTPUTDIR --throws-exception-on-error --description-file $$file; \
#		done; \
#	fi

#giws-exception:
#	@GIWS_OUTPUTDIR=src/jni/;\
#	echo "GIWS: Generation of exception class ..."; \
#	$(GIWS_BIN) --generate-exception-class --output-dir $$GIWS_OUTPUTDIR 

macros:
	-@( if test ! -x $(top_builddir)/scilab-bin; then \
		echo "Error : Cannot build $< : Scilab has not been built"; \
	else \
		$(top_builddir)/bin/scilab -ns -nwni -e "exec('macros/buildmacros.sce');quit;";\
	fi)

# Removes the macros
clean-macros:
# Removes macros (*.bin generated from .sci)
	@for dir in $(MACRODIRS) $(MACROSDIRSEXT) ; do \
		echo "rm -f $(builddir)/$$dir/$(MACROBINMASK)"; \
		rm -f $(builddir)/$$dir/$(MACROBINMASK); \
	done

test:
# More tests could be added here
	@if test -z "$(USEANT)"; then USEANT=0; else USEANT=1; fi; \
	if test -f build.xml -a $$USEANT -eq 1; then \
		$(ANT) test; \
	fi

all-local: $(TARGETS_ALL)

.sci.bin:
	-@( if test ! -x $(top_builddir)/scilab-bin; then \
	echo "Error : Cannot build $< : Scilab has not been build"; \
	else \
	echo "Creating $@"; \
	$(top_builddir)/bin/scilab -ns -nwni -e "exec('$(abs_srcdir)/$<');save('$(abs_srcdir)/$@');exit;"; \
	fi )

install-html-local:

install-data-local-local:
# Mainly for javasci
	@if test -d $(srcdir)/javadoc; then \
		cp -R $(srcdir)/javadoc $(DESTDIR)/$(mydatadir)/; \
	fi
# If the user wants the help sources to be installed
	@echo "-------- Install of XML sources of help files --------"; \
	for lang in $(ALL_LINGUAS); do \
	 if test -d $(srcdir)/help/$$lang; then \
	  $(mkinstalldirs) $(DESTDIR)$(pkgdocdir)/help/$$lang && \
		if ls -lLd $(srcdir)/help/$$lang/$(DOCMASKXML) >/dev/null 2>&1; then \
		  for file in $(srcdir)/help/$$lang/$(DOCMASKXML) ; do \
		    echo "$(INSTALL_DATA) $$file $(DESTDIR)$(pkgdocdir)/help/$$lang" ; \
	    	$(INSTALL_DATA) "$$file" $(DESTDIR)$(pkgdocdir)/help/$$lang ; \
		  done ; \
		fi; \
	 fi; \
	done; \
	@echo "-------- Install of MathML sources --------"; \
	 if test -d $(srcdir)/help/mml/; then \
	  $(mkinstalldirs) $(DESTDIR)$(pkgdocdir)/help/mml/ && \
		if ls -lLd $(srcdir)/help/mml/$(DOCMASKMML) >/dev/null 2>&1; then \
		  for file in $(srcdir)/help/mml/$(DOCMASKMML) ; do \
		    echo "$(INSTALL_DATA) $$file $(DESTDIR)$(pkgdocdir)/help/mml" ; \
	    	$(INSTALL_DATA) "$$file" $(DESTDIR)$(pkgdocdir)/help/mml ; \
		  done ; \
		fi; \
	fi
install-data-local:
# Install the tests
	@echo "-------- Install tests (if any) --------"; \
	for dir in $(TESTS_DIR) $(TESTS_DIREXT) ; do \
	  if test -d $(srcdir)/$$dir/; then \
	    $(mkinstalldirs) $(DESTDIR)$(pkgmacrosdir)/$$dir && \
		  for file in `find $(srcdir)/$$dir | sed "s|^$(srcdir)/$$dir||" 2>/dev/null`; do \
		    if test -d "$(srcdir)/$$dir/$$file"; then \
			  echo $(mkinstalldirs) $(DESTDIR)$(pkgmacrosdir)/$$dir/$$file; \
			  $(mkinstalldirs) "$(DESTDIR)$(pkgmacrosdir)/$$dir/$$file"; \
		    else \
		      echo "$(INSTALL_DATA) $(srcdir)/$$dir/$$file $(DESTDIR)$(pkgmacrosdir)/`dirname $$dir/$$file`" ; \
	    	  $(INSTALL_DATA) "$(srcdir)/$$dir/$$file" "$(DESTDIR)$(pkgmacrosdir)/`dirname $$dir/$$file`" ; \
		    fi \
		  done; \
	  fi; \
	done
# Install the help chapter
	@echo "-------- Install the help chapter (if any) --------"; \
	for lang in $(HELP_CHAPTERLANG); do \
		HELPFILE=$(srcdir)/$(HELP_CHAPTERDIR)$$lang/$(HELP_CHAPTERFILE); \
		if test -f $$HELPFILE; then \
			echo $(mkinstalldirs) $(DESTDIR)$(pkgdocdir)/$(HELP_CHAPTERDIR)/$$lang/; \
			$(mkinstalldirs) $(DESTDIR)$(pkgdocdir)/$(HELP_CHAPTERDIR)/$$lang/; \
			echo $(INSTALL_DATA) $$HELPFILE $(DESTDIR)$(pkgdocdir)/$$HELPFILE; \
			$(INSTALL_DATA) $$HELPFILE $(DESTDIR)$(pkgdocdir)/$$HELPFILE; \
		fi; \
	done
# Install the demos & examples
	@echo "-------- Install demos & examples (if any) --------"; \
	for dir in $(DEMOS_DIR) $(DEMOS_DIREXT) $(EXAMPLES_DIR) $(EXAMPLES_DIREXT) ; do \
	  if test -d $(srcdir)/$$dir/; then \
	    $(mkinstalldirs) $(DESTDIR)$(pkgdocdir)/$$dir && \
		  for file in `find $(srcdir)/$$dir | sed "s|^$(srcdir)/$$dir||" 2>/dev/null`; do \
		    if test -d "$(srcdir)/$$dir/$$file"; then \
			  echo $(mkinstalldirs) $(DESTDIR)$(pkgdocdir)/$$dir/$$file; \
			  $(mkinstalldirs) "$(DESTDIR)$(pkgdocdir)/$$dir/$$file"; \
		    else \
		      echo "$(INSTALL_DATA) $(srcdir)/$$dir/$$file $(DESTDIR)$(pkgdocdir)/`dirname $$dir/$$file`" ; \
	    	  $(INSTALL_DATA) "$(srcdir)/$$dir/$$file" "$(DESTDIR)$(pkgdocdir)/`dirname $$dir/$$file`" ; \
		    fi \
		  done; \
	  fi; \
	done
# Install the macros
	@echo "-------- Install macros (if any) --------"; \
	for dir in $(MACRODIRS) $(MACROSDIRSEXT) ; do \
	  $(mkinstalldirs) $(DESTDIR)$(pkgmacrosdir)/$$dir && \
		if test -d $(srcdir)/$$dir/; then \
			FILELIST="$(srcdir)/$$dir/$(MACROMASK) $(srcdir)/$$dir/$(MACROBINMASK) $(srcdir)/$$dir/$(MACROBUILDMASK) $(srcdir)/$$dir/names $(srcdir)/$$dir/lib";\
			if test -n "$(MACROSSPECIALEXT)"; then \
				specialExtDir=""; \
				for specialExt in $(MACROSSPECIALEXT); do \
					specialExtDir="$$specialExtDir $(srcdir)/$$dir/$$specialExt"; \
				done; \
				FILELIST="$$FILELIST $$specialExtDir"; \
			fi; \
		  for file in `ls -1 $$FILELIST 2>/dev/null`; do \
		    echo "$(INSTALL_DATA) $$file $(DESTDIR)$(pkgmacrosdir)/$$dir" ; \
	    	$(INSTALL_DATA) "$$file" $(DESTDIR)$(pkgmacrosdir)/$$dir ; \
		  done; \
		fi; \
	done
# Install java files (.jar)
	@if ls -lLd $(srcdir)/$(JARDIR)$(JARMASK) >/dev/null 2>&1; then \
	echo "-------- Install jar files --------"; \
    $(mkinstalldirs) $(DESTDIR)$(pkgdocdir)/$(JARDIR); \
	  for file in $(srcdir)/$(JARDIR)$(JARMASK); do\
		    echo "$(INSTALL_DATA) $$file $(DESTDIR)$(pkgdocdir)/$(JARDIR)" ; \
	    	$(INSTALL_DATA) "$$file" $(DESTDIR)$(pkgdocdir)/$(JARDIR) ; \
	  done ; \
	fi

########### CLEAN ###################
# Clean help (generated automatically by Scilab)
# It used to clean the macro (clean-macros) but this was causing
# make clean && make to fail Scilab startup
clean-local: clean-java
#clean-local:

distclean-local:
	rm -f $(builddir)/help/*/.last_successful_build_javaHelp $(builddir)/help/*/.list_*

.PHONY: macros java swig giws

jit_ocaml.o: src/c/jit_ocaml.c
	ocamlopt -c -I includes -fPIC src/c/jit_ocaml.c

libscijit_ocaml-runtime.o: $(OCAML_CMXS) jit_ocaml.o libasmrun.a
	$(OCAMLOPT) -o libscijit_ocaml-runtime.o -output-obj $(OCAML_CMXS)

libasmrun.a:
	cp $(OCAMLC_WHERE)/libasmrun.a .

depend_ocaml:
	$(OCAMLDEP) -native $(OCAML_INCL) $(OCAML_MLS) $(OCAML_MLIS) > .depend_ocaml
src/ocaml/scilabAst.cmo :
src/ocaml/scilabAst.cmx :
src/ocaml/scilabAstPrinter.cmo : src/ocaml/scilabAst.cmx \
    src/ocaml/scilabAstPrinter.cmi
src/ocaml/scilabAstPrinter.cmx : src/ocaml/scilabAst.cmx \
    src/ocaml/scilabAstPrinter.cmi
src/ocaml/scilabString2Ast.cmo : src/ocaml/scilabAst.cmx \
    src/ocaml/scilabString2Ast.cmi
src/ocaml/scilabString2Ast.cmx : src/ocaml/scilabAst.cmx \
    src/ocaml/scilabString2Ast.cmi
src/ocaml/scilabCallbacks.cmo : src/ocaml/scilabString2Ast.cmi \
    src/ocaml/scilabAstPrinter.cmi src/ocaml/scilabCallbacks.cmi
src/ocaml/scilabCallbacks.cmx : src/ocaml/scilabString2Ast.cmx \
    src/ocaml/scilabAstPrinter.cmx src/ocaml/scilabCallbacks.cmi
src/ocaml/scilabAstPrinter.cmi : src/ocaml/scilabAst.cmx
src/ocaml/scilabString2Ast.cmi : src/ocaml/scilabAst.cmx
src/ocaml/scilabCallbacks.cmi :

.ml.cmx:
	$(OCAMLOPT) $(OPTFLAGS) -c $<

.mli.cmi:
	$(OCAMLOPT) $(OPTFLAGS) -c $<

.mll.ml:
	$(OCAMLLEX) $<

.mly.ml:
	$(OCAMLYACC) $<

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
